import './js/mobile-menu';
import './js/swiper';
import './js/filters';
import './js/pop-up';
import './js/form';
import './js/api/popular-api';
import './js/categories';
import './js/renderCards';
import './js/modal';
